// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectLab.Data;

#nullable disable

namespace ProjectLab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251012104914_Std-Table")]
    partial class StdTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectLab.Models.Student", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSN"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SSN");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            SSN = 1001,
                            Address = "123 Maple Street, Springfield",
                            Age = 20,
                            Email = "alice.johnson@example.com",
                            Image = "alice.jpg",
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            SSN = 1002,
                            Address = "456 Oak Avenue, Lincoln",
                            Age = 22,
                            Email = "ben.carter@example.com",
                            Image = "benjamin.jpg",
                            Name = "Benjamin Carter"
                        },
                        new
                        {
                            SSN = 1003,
                            Address = "789 Pine Road, Riverside",
                            Age = 19,
                            Email = "chloe.martinez@example.com",
                            Image = "chloe.jpg",
                            Name = "Chloe Martinez"
                        },
                        new
                        {
                            SSN = 1004,
                            Address = "321 Birch Lane, Cedar City",
                            Age = 21,
                            Email = "daniel.kim@example.com",
                            Image = "daniel.jpg",
                            Name = "Daniel Kim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
